"""日志表增加字段

Revision ID: fcc263f089e0
Revises: 
Create Date: 2025-03-24 16:13:41.140893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc263f089e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('browser', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('browser_version', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('os', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('os_version', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('device', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_column('device')
        batch_op.drop_column('os_version')
        batch_op.drop_column('os')
        batch_op.drop_column('browser_version')
        batch_op.drop_column('browser')
        batch_op.drop_column('city')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
